/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wueb;

/**
 *
 * @author aschoenf
 */
public class guiWUEB extends javax.swing.JFrame {

    /**
     * Creates new form guiWUEB
     */
    public guiWUEB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitel = new javax.swing.JLabel();
        lblEinnahmen = new javax.swing.JLabel();
        lblAusgaben = new javax.swing.JLabel();
        lblUeberschuss = new javax.swing.JLabel();
        btmNeueBuchung = new javax.swing.JButton();
        tfEinnahmen = new javax.swing.JTextField();
        tfAusgaben = new javax.swing.JTextField();
        tfUeberschuss = new javax.swing.JTextField();
        lblTitel1 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();

        lblTitel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblTitel.setText("Neue Buchung - WUEB");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblEinnahmen.setText("Einnahmen:");

        lblAusgaben.setText("Ausgaben:");

        lblUeberschuss.setText("Überschuss:");

        btmNeueBuchung.setText("Neue Buchung");
        btmNeueBuchung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmNeueBuchungActionPerformed(evt);
            }
        });

        tfEinnahmen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEinnahmenActionPerformed(evt);
            }
        });

        lblTitel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblTitel1.setText("Was über Bilanzen - WUEB");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEinnahmen, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUeberschuss, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfEinnahmen)
                            .addComponent(tfUeberschuss, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAusgaben)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfAusgaben, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btmNeueBuchung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25))
                    .addComponent(lblTitel1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lblTitel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEinnahmen)
                    .addComponent(lblAusgaben)
                    .addComponent(tfEinnahmen, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAusgaben, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUeberschuss)
                    .addComponent(btmNeueBuchung)
                    .addComponent(tfUeberschuss, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmNeueBuchungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmNeueBuchungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btmNeueBuchungActionPerformed

    private void tfEinnahmenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEinnahmenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEinnahmenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guiWUEB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guiWUEB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guiWUEB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guiWUEB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guiWUEB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmNeueBuchung;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lblAusgaben;
    private javax.swing.JLabel lblEinnahmen;
    private javax.swing.JLabel lblTitel;
    private javax.swing.JLabel lblTitel1;
    private javax.swing.JLabel lblUeberschuss;
    private javax.swing.JTextField tfAusgaben;
    private javax.swing.JTextField tfEinnahmen;
    private javax.swing.JTextField tfUeberschuss;
    // End of variables declaration//GEN-END:variables
}
